### ISSUE TITLE
nbHits on /packs shows 15, yet only returns 12

### ISSUE THREAD

**Issue by audn** [discordlist-gg/Cronos#20]
is it counting private packs too?

https://beta.discordlist.gg/packs

**Comment by audn** [comment]
found out this was because we hide packs with 0 bots in it

can you return results - packs with less than 1 bot?

**Comment by ChillFish8** [comment]
No, It's the same issue as /bots has where the aggregator ignores the tag/category filters -> Which the nbhits get's it's count from.

Private and hidden packs are never counted as they're never indexed.
